name: Deploy

on: 
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run dotnet build
      run: dotnet build --no-restore --configuration release 
  
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run dotnet test
      run: dotnet test --no-build --verbosity normal  
  
  publish_and_copy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Run dotnet publish
        run: dotnet publish --configuration release --output deploy
      - name: Copy published files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "/home/runner/work/MinimalApp/MinimalApp/deploy"
          target: "${{ secrets.SERVER_DIRECTORY }}"
          overwrite: true
          rm: true
  server_commands:
    needs: [publish_and_copy]
    runs-on: ubuntu-latest
    steps:
      - name: Restart kestrel service on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: sudo systemctl restart kestrel-minimalapp.service
